module.exports = [
  {
    name: "Clement",
    email: "clement@gmail.com",
    contact: "123456",
    address: "Clementi",
    unit: "11-32",
    zipcode: "123456",
    type: "plumbing",
    date: "01/01/2021",
    comments: "I need help with xx",
    accepted: false,
    completed: false,
  },
  {
    name: "Ernest",
    email: "ernest@outlook.sg",
    contact: "123456",
    address: "Sin Ming",
    unit: "11-11",
    zipcode: "556677",
    type: "cleaning",
    date: "01/13/2022",
    comments: "I need help with yy",
    accepted: false,
    completed: false,
  },
  {
    name: "Jeng Mun",
    email: "jengmun@yahoo.com",
    contact: "123456",
    address: "Jurong",
    unit: "10-01",
    zipcode: "901132",
    type: "grocery",
    date: "12/01/2021",
    comments: "I need help with zz",
    accepted: false,
    completed: false,
  },
];
