module.exports = [
  {
    username: "1",
    password: "1",
    name: "Ernest",
    email: "ernest@outlook.sg",
    contact: "123456",
    address: "Sin Ming",
    unit: "11-11",
    zipcode: "556677",
  },
  {
    username: "2",
    password: "2",
    name: "Jeng Mun",
    email: "jengmun@yahoo.com",
    contact: "123456",
    address: "Jurong",
    unit: "10-01",
    zipcode: "901132",
  },
  {
    username: "3",
    password: "3",
    name: "Clement",
    email: "clement@gmail.com",
    contact: "123456",
    address: "Clementi",
    unit: "11-32",
    zipcode: "123456",
  },
  {
    username: "4",
    password: "4",
    name: "Alex",
    email: "ernest@outlook.sg",
    contact: "123456",
    address: "Sin Ming",
    unit: "11-11",
    zipcode: "556677",
  },
  {
    username: "5",
    password: "5",
    name: "Wei Jie",
    email: "ernest@outlook.sg",
    contact: "123456",
    address: "Sin Ming",
    unit: "11-11",
    zipcode: "556677",
  },
];
